Minor improvements to stresstest and nw_stresstest scripts

diff --git a/Colossus/bin/nw_stresstest_client b/Colossus/bin/nw_stresstest_client
--- a/Colossus/bin/nw_stresstest_client
+++ b/Colossus/bin/nw_stresstest_client
@@ -22,11 +22,9 @@
 
 done=no
 
-playername=$USERNAME
 
 while [ $# -gt 0 -a "$done" = "no" ]
 do
-
   case $1 in
     --cleansn*|-C)
         echo "Setting delete_snaps to yes"
@@ -46,6 +44,31 @@ do
   esac
   shift
 done
+
+if [ -n "$playername" ]
+then
+    echo "OK, playername was set to '$playername'."
+elif [ -n "$USERNAME" ]
+then
+    playername=$USERNAME
+elif [ -n "$USER" ]
+then
+    playername=$USER
+elif [ -n "$LOGNAME" ]
+then
+    playername=$LOGNAME
+else
+    echo "Can't determine a user name - use '-m' or set one of the environment variables!"
+    exit 1
+fi
+
+LOGPROPFILENAME=logging.properties.$playername
+
+if [ ! -e $LOGPROPFILENAME ]
+then
+    echo "Please create a logging properties file called '$LOGPROPFILENAME'!"
+    exit 1
+fi
 
 mkdir -p ./tmp/stresstest
 
@@ -74,7 +97,7 @@ while true
 do 
     echo -e "\nStarting client $playername again\n" 
     echo -e "$CR\nStarting client $playername again$CR" >> $LOG
-    CMD="java -Djava.util.logging.config.file=logging.properties $INTERNALROUNDS -Xmx256M -jar Colossus.jar -c -m $playername -g -q $1 $2 $3 $4 $5 $6 $7 $8 $9"
+    CMD="java -Djava.util.logging.config.file=logging.properties.$playername $INTERNALROUNDS -Xmx256M -jar Colossus.jar -c -m $playername -g -q $1 $2 $3 $4 $5 $6 $7 $8 $9"
     echo $CMD
     echo $CMD >> $LOG 2>&1
     $CMD      >> $LOG 2>&1
