Bail out early if Colossus.jar does not exist.
git-svn-id: svn://localhost/tmp/s2g/colossus.svn/trunk@3060 c5679a2a-0e0e-0410-bba2-8642b794b8c1

diff --git a/Colossus/fancy_stresstest b/Colossus/fancy_stresstest
--- a/Colossus/fancy_stresstest
+++ b/Colossus/fancy_stresstest
@@ -41,6 +41,14 @@
 #   -A or --aggressive      = grab more resources from the OS
 
 
+if [ ! -e Colossus.jar ]
+then
+  echo ""
+  echo "Can't run stresstest: file Colossus.jar does not exist!"
+  echo ""
+  exit 1
+fi
+
 # this defines the two functions to get just the added part from the log:
 . logFollowing.SH
 
