fancy_stresstest can now also do Remote stresstests: -R <N> makes it expect N remote clients; (one have to start as many nw_stresstest_clients as needed additionally)
git-svn-id: svn://localhost/tmp/s2g/colossus.svn/trunk@2690 c5679a2a-0e0e-0410-bba2-8642b794b8c1

diff --git a/Colossus/fancy_stresstest b/Colossus/fancy_stresstest
--- a/Colossus/fancy_stresstest
+++ b/Colossus/fancy_stresstest
@@ -16,10 +16,10 @@
 # Perhaps this replace the original stresstest script completely,
 # but I was not sure, perhaps someone would rather like to stay
 # with the old one.
-
+#
 # Usage:
 #
-# ./fancy_stresstest [-C] [-W] [-V <variants>] [ -N <count>] [ -- <Colossus-Options> ]
+# ./fancy_stresstest [-C] [-W] [-V <variants>] [ -N <count>] [ -R <count> ] [ -- <Colossus-Options> ]
 #
 # That means, all options not meant to the script but rather that they
 # shall be given to the Colossus commandline,  must come after an "--".
@@ -29,10 +29,20 @@
 #                             for AI-only games there is no board visible)
 #   -V or --variants        = run stresstest only for this/these variants
 #   -N or --count           = stop latest after N counts
+#   -R or --remote          = nr. of remote clients
 
 FORCEBOARD=""
 done=no
 variants=""
+
+humans=-u0
+AIs=6
+MyName=MyName
+if [ "X$USERNAME" != "X" ]
+then
+  MyName=$USERNAME
+fi
+
 
 while [ $# -gt 0 -a "$done" = "no" ]
 do
@@ -45,24 +55,36 @@ do
         echo "Setting forceViewWindow to yes"
         FORCEBOARD=-Dnet.sf.colossus.forceViewBoard=yes
         ;;
-     --variants|-V)
+    --variants|-V)
         shift
         variants=$1
         echo "Setting list of variants to '$variants'"
         ;;
-     --count|-N)
-       shift
-       maxcount=$1
-       echo "Setting maxcount to '$maxcount'"
-       ;;
-     --)
-       done=yes
-       ;;
-      *)
-       echo "Option '$1' is not meaningful to stresstest script itself - ignored."
-       echo "Put options meant to starting Colossus.jar itself after a -- separator"
-       exit 1
-
+    --count|-N)
+        shift
+        maxcount=$1
+        echo "Setting maxcount to '$maxcount'"
+        ;;
+    --remote|-R)
+        shift
+        nrc=$1
+        # That thing with the remote clients currently works only well if at 
+        # least one human player is there, too (to get a masterboard). 
+        # So, let's add one:
+        remoteclients="-n$1 -S -m$MyName -A"
+        humans=-u1
+        echo "Setting remoteclients to '$remoteclients'"
+        # 5 instead of 6, because of the one human:
+        AIs=`expr 5 - $nrc`
+        echo "Setting AIs then to '$AIs'"
+        ;;
+    --)
+        done=yes
+        ;;
+    *)
+        echo "Option '$1' is not meaningful to stresstest script itself - aborted."
+        echo "Put options meant to starting Colossus.jar itself after a -- separator"
+        exit 1
   esac
   shift
 done
@@ -117,7 +139,9 @@ then
 fi
 
 # ----------------------------------------------------------------------
-# Now loop forever, or until a flag file "stop.flag" is created.
+# Now loop forever, or until a flag file "stop.flag" is created
+# or, if -N was given, i reaches iMax (i at start + N-count).
+#
 # Continue with game number "i" from a file i.
 # If colossus game exited with non-zero exit code (or someone created
 # a file "backup.flag" while game still running), copy all relevant
@@ -158,12 +182,17 @@ do
     variant=`echo $variants | cut -d " " -f $variantnr`
     # variant=Unified
 
+    timestamp=`date +'%d.%m.%Y %T'`
+
     i=`expr $i + 1`
     echo -e $i > i
-    echo -e "\nStarting game #$i as variant $variant"
-    echo -e "$CR\nStarting game #$i as variant $variant$CR" >> log
+    echo -e "\n$timestamp: Starting game #$i as variant $variant"
+    echo -e "$CR\n$timestamp: Starting game #$i as variant $variant$CR" >> log
+    
+    CMD="java -Djava.util.logging.config.file=logging.properties $FORCEBOARD -Xmx128M -jar Colossus.jar $humans -i$AIs $remoteclients -qgS -d 1 --variant $variant $1 $2 $3 $4 $5 $6 $7 $8 $9"
+    echo $CMD
+    $CMD >> log 2>&1;
 
-    java -Djava.util.logging.config.file=logging.properties $FORCEBOARD -Xmx128M -jar Colossus.jar -i 6 -q -g -d 1 --variant $variant $1 $2 $3 $4 $5 $6 $7 $8 $9 >> log 2>&1;
     ec=$?
     mkbackup=n
     if [ $ec -ne 0 ]
@@ -196,10 +225,16 @@ do
     fi
     if [ "X$iMax" != "X" ]
     then
-      if [ $i -gt $iMax ]
+      if [ $i -ge $iMax ]
       then
         echo -e    "\nReady: i=$i, $maxcount rounds run - exiting..."
         echo -e "$CR\nReady: i=$i, $maxcount rounds run - exiting...$CR" >> log
+
+        # if relevant, tell the clients to stop, too:
+        if [ "X$remoteclients" != "X" ]
+        then
+          touch stop.flag
+        fi
 	exit
       fi
     fi
@@ -207,7 +242,6 @@ do
     then
       echo -e    "\nFlagfile stop.flag found - exiting..."
       echo -e "$CR\nFlagfile stop.flag found - exiting...$CR" >> log
-      rm -f stop.flag
       exit
     fi
 done
